version: 2 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/mern-starter # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.13.0 # ...with this image as the primary container; this is where all `steps` will run
      - image: mongo:4.2.0 # and this image as the secondary service container
      - image: circleci/postgres:9.6-alpine # Postgres
        environment:
          POSTGRES_USER: safescrow_user
          POSTGRES_DB: safescrow_db
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      #   - restore_cache: # special step to restore the dependency cache
      #       # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      #       key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      #   - save_cache: # special step to save the dependency cache
      #       key: dependency-cache-{{ checksum "package-lock.json" }}
      #       paths:
      #         - ./node_modules
      - run: # run tests
          name: Migrate database and Run Test
          command: npm test
          environment:
            JWT_SECRET: 'SecretOrPrivateKey'
            PASSWORD_RESET_SECRET: 'SecretOrPrivateKey'
            DEV_DB_URL: 'postgres://safescrow_user@localhost:5432/safescrow_db'
      - run: # Drop DB
          name: Drop Database
          command: npm run migrate:drop
          environment:
            DEV_DB_URL: 'postgres://safescrow_user@localhost:5432/safescrow_db'
      - run: # run coverage report
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
    #   - store_artifacts: # special step to save test results as as artifact
    #       # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
    #       path: test-results.xml
    #       prefix: tests
    #   - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
    #       path: coverage
    #       prefix: coverage
    #   - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
    #       path: test-results.xml
    #   # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
